name: build-3dsx

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 3ds packages
        run: |
          dkp-pacman -Syu --noconfirm
          dkp-pacman -S --noconfirm 3ds-dev

      - name: Build
        run: |
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my3dsapp-build
          path: |
            *.3dsx
            *.smdh
