steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 3DS libraries
        run: |
          set -e
          echo "Installing 3DS devkit libraries..."
          dkp-pacman -Sy --noconfirm 3ds-dev || true
          dkp-pacman -S --needed --noconfirm 3ds-citro3d 3ds-citro2d 3ds-libctru || true
          ls -R /opt/devkitpro/libctru || true

      - name: Build
        env:
          DEVKITPRO: /opt/devkitpro
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my3dsapp-build
          path: |
            *.3dsx
            *.smdh
