name: build-3dsx

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Das Image enthält bereits alles Nötige.
      - name: Verify toolchain
        run: |
          echo "Listing /usr/local/devkitPro:"
          ls -la /usr/local/devkitPro || true
          test -f /usr/local/devkitPro/3ds_rules && echo "3ds_rules OK"

      - name: Build
        env:
          DEVKITPRO: /usr/local/devkitPro
        run: |
          echo "Using DEVKITPRO=$DEVKITPRO"
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my3dsapp-build
          path: |
            *.3dsx
            *.smdh
